version = 0.1
[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "nft-scam-predictor-PROD"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dznr37onm9nt"
s3_prefix = "nft-scam-predictor-PROD"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["InferenceFunction=692666379301.dkr.ecr.eu-central-1.amazonaws.com/nftscampredictorprodfbdc98f8/inferencefunction7c73919drepo"]

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "nft-scam-predictor-DEV"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dznr37onm9nt"
s3_prefix = "nft-scam-predictor-DEV"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["InferenceFunction=692666379301.dkr.ecr.eu-central-1.amazonaws.com/nftscampredictordev48e69bc6/inferencefunction7c73919drepo"]