from enum import Enum


class NftScamResponse(Enum):
    CHECKS_PASSED = "CHECKS_PASSED"
    SUSPECTED_MALICIOUS = "SUSPECTED_MALICIOUS"
    DATA_FETCHING_ERROR = "DATA_FETCHING_ERROR"
    WRONG_INPUT = "INVALID_INPUT"
